export type Category =
  | "cpu"
  | "motherboard"
  | "gpu"
  | "ram"
  | "storage"
  | "cooling"
  | "psu"
  | "case"
  | "os"
  | "peripheral"
  | "monitor"
  | "extra";

export interface Part {
  id: string;
  category: Category;
  brand: string;
  name: string;
  price: number;
  power: number;
  socket?: string;
  chipset?: string;
  wifi?: boolean;
  cores?: number;
  threads?: number;
  boostGhz?: number;
  cacheMb?: number;
  vramGb?: number;
  memoryGb?: number;
  speed?: string;
  capacityTb?: number;
  type?: string;
  height?: number;
  radiatorSupport?: number;
  watts?: number;
  rating?: string;
  form?: string;
  maxGpuLength?: number;
  maxCoolerHeight?: number;
  fans?: string;
  kind?: string;
  monitorSize?: string;
  displayRes?: "1080p" | "1440p" | "4k";
  refreshHz?: number;
  panel?: "IPS" | "VA" | "OLED";
  noOs?: boolean;
  perf?: number;
  gaming?: number;
  ai?: number;
  render?: number;
  features?: string[];
  recommended?: boolean;
  best?: boolean;
  // Wizard grouping fields
  family?: string;
  size?: string;
  lengthMm?: number;
  speedMhz?: number;
  pcieGen?: "Gen 3" | "Gen 4" | "Gen 5";
  ramMaxMhz?: number;
  tier?: "mid" | "high";
  formSupport?: string[];
  radiatorMax?: number;
  psuMin?: number;
}

export interface CategoryDef {
  key: Category;
  label: string;
  icon: string;
  description: string;
}

export const categories: Record<Category, CategoryDef> = {
  cpu: { key: "cpu", label: "Procesador", icon: "cpu", description: "El cerebro del sistema" },
  motherboard: { key: "motherboard", label: "Placa base", icon: "motherboard", description: "La plataforma que conecta todo" },
  gpu: { key: "gpu", label: "Gráfica", icon: "gpu", description: "El corazón para jugar" },
  ram: { key: "ram", label: "Memoria RAM", icon: "ram", description: "Multitarea sin límites" },
  storage: { key: "storage", label: "Almacenamiento", icon: "storage", description: "Velocidad y espacio" },
  cooling: { key: "cooling", label: "Refrigeración", icon: "cooling", description: "Mantén las temperaturas bajas" },
  psu: { key: "psu", label: "Fuente de alimentación", icon: "psu", description: "Energía limpia y segura" },
  case: { key: "case", label: "Caja", icon: "case", description: "El corazón de tu setup" },
  os: { key: "os", label: "Sistema operativo", icon: "os", description: "El software que lo gobierna" },
  peripheral: { key: "peripheral", label: "Periférico", icon: "peripheral", description: "Completa tu experiencia" },
  monitor: { key: "monitor", label: "Monitor", icon: "monitor", description: "La ventana a tus juegos" },
  extra: { key: "extra", label: "Extras", icon: "extra", description: "El toque premium" },
};

export const cpuParts: Part[] = [
  {
    id: "cpu-r5-7600",
    category: "cpu",
    brand: "AMD",
    family: "Ryzen 5",
    name: "Ryzen 5 7600",
    price: 209,
    power: 65,
    socket: "AM5",
    cores: 6,
    threads: 12,
    boostGhz: 5.1,
    cacheMb: 48,
    perf: 62,
    gaming: 66,
    ai: 40,
  },
  {
    id: "cpu-r5-7600x",
    category: "cpu",
    brand: "AMD",
    family: "Ryzen 5",
    name: "Ryzen 5 7600X",
    price: 219,
    power: 105,
    socket: "AM5",
    cores: 6,
    threads: 12,
    boostGhz: 5.3,
    cacheMb: 38,
    perf: 64,
    gaming: 69,
    ai: 42,
  },
  {
    id: "cpu-r5-9600x",
    category: "cpu",
    brand: "AMD",
    family: "Ryzen 5",
    name: "Ryzen 5 9600X",
    price: 269,
    power: 65,
    socket: "AM5",
    cores: 6,
    threads: 12,
    boostGhz: 5.4,
    cacheMb: 48,
    perf: 68,
    gaming: 70,
    ai: 45,
  },
  {
    id: "cpu-r7-7700x",
    category: "cpu",
    brand: "AMD",
    family: "Ryzen 7",
    name: "Ryzen 7 7700X",
    price: 329,
    power: 105,
    socket: "AM5",
    cores: 8,
    threads: 16,
    boostGhz: 5.4,
    cacheMb: 48,
    perf: 78,
    gaming: 78,
    ai: 52,
  },
  {
    id: "cpu-r7-9700x",
    category: "cpu",
    brand: "AMD",
    family: "Ryzen 7",
    name: "Ryzen 7 9700X",
    price: 399,
    power: 105,
    socket: "AM5",
    cores: 8,
    threads: 16,
    boostGhz: 5.5,
    cacheMb: 48,
    perf: 85,
    gaming: 80,
    ai: 58,
  },
  {
    id: "cpu-r7-7800x3d",
    category: "cpu",
    brand: "AMD",
    family: "Ryzen 7",
    name: "Ryzen 7 7800X3D",
    price: 419,
    power: 120,
    socket: "AM5",
    cores: 8,
    threads: 16,
    boostGhz: 5.0,
    cacheMb: 96,
    perf: 92,
    gaming: 97,
    ai: 55,
    best: true,
    recommended: true,
  },
  {
    id: "cpu-r7-9800x3d",
    category: "cpu",
    brand: "AMD",
    family: "Ryzen 7",
    name: "Ryzen 7 9800X3D",
    price: 515,
    power: 120,
    socket: "AM5",
    cores: 8,
    threads: 16,
    boostGhz: 5.2,
    cacheMb: 104,
    perf: 98,
    gaming: 100,
    ai: 60,
    recommended: true,
  },
  {
    id: "cpu-r9-7950x3d",
    category: "cpu",
    brand: "AMD",
    family: "Ryzen 9",
    name: "Ryzen 9 7950X3D",
    price: 589,
    power: 120,
    socket: "AM5",
    cores: 16,
    threads: 32,
    boostGhz: 5.7,
    cacheMb: 128,
    perf: 105,
    gaming: 92,
    ai: 85,
  },
  {
    id: "cpu-r9-9950x",
    category: "cpu",
    brand: "AMD",
    family: "Ryzen 9",
    name: "Ryzen 9 9950X",
    price: 629,
    power: 170,
    socket: "AM5",
    cores: 16,
    threads: 32,
    boostGhz: 5.7,
    cacheMb: 80,
    perf: 118,
    gaming: 85,
    ai: 95,
  },
  {
    id: "cpu-r9-9900x",
    category: "cpu",
    brand: "AMD",
    family: "Ryzen 9",
    name: "Ryzen 9 9900X",
    price: 429,
    power: 120,
    socket: "AM5",
    cores: 12,
    threads: 24,
    boostGhz: 5.6,
    cacheMb: 76,
    perf: 96,
    gaming: 76,
    ai: 75,
  },
  {
    id: "cpu-r9-9950x3d",
    category: "cpu",
    brand: "AMD",
    family: "Ryzen 9",
    name: "Ryzen 9 9950X3D",
    price: 699,
    power: 170,
    socket: "AM5",
    cores: 16,
    threads: 32,
    boostGhz: 5.7,
    cacheMb: 128,
    perf: 116,
    gaming: 99,
    ai: 95,
    recommended: true,
  },
  {
    id: "cpu-i5-13600k",
    category: "cpu",
    brand: "Intel",
    family: "Core i5",
    name: "Core i5-13600K",
    price: 239,
    power: 180,
    socket: "LGA1700",
    cores: 14,
    threads: 20,
    boostGhz: 5.1,
    cacheMb: 24,
    perf: 78,
    gaming: 73,
    ai: 55,
  },
  {
    id: "cpu-i5-14400",
    category: "cpu",
    brand: "Intel",
    family: "Core i5",
    name: "Core i5-14400",
    price: 189,
    power: 148,
    socket: "LGA1700",
    cores: 10,
    threads: 16,
    boostGhz: 4.7,
    cacheMb: 20,
    perf: 66,
    gaming: 60,
    ai: 45,
  },
  {
    id: "cpu-i5-14600k",
    category: "cpu",
    brand: "Intel",
    family: "Core i5",
    name: "Core i5-14600K",
    price: 259,
    power: 181,
    socket: "LGA1700",
    cores: 14,
    threads: 20,
    boostGhz: 5.3,
    cacheMb: 34,
    perf: 82,
    gaming: 84,
    ai: 58,
  },
  {
    id: "cpu-i7-14700k",
    category: "cpu",
    brand: "Intel",
    family: "Core i7",
    name: "Core i7-14700K",
    price: 379,
    power: 253,
    socket: "LGA1700",
    cores: 20,
    threads: 28,
    boostGhz: 5.6,
    cacheMb: 40,
    perf: 95,
    gaming: 90,
    ai: 72,
  },
  {
    id: "cpu-i9-14900k",
    category: "cpu",
    brand: "Intel",
    family: "Core i9",
    name: "Core i9-14900K",
    price: 549,
    power: 253,
    socket: "LGA1700",
    cores: 24,
    threads: 32,
    boostGhz: 6.0,
    cacheMb: 36,
    perf: 108,
    gaming: 92,
    ai: 80,
  },
  {
    id: "cpu-i5-245k",
    category: "cpu",
    brand: "Intel",
    family: "Core Ultra 5",
    name: "Core Ultra 5 245K",
    price: 309,
    power: 150,
    socket: "LGA1851",
    cores: 14,
    threads: 14,
    boostGhz: 5.2,
    cacheMb: 24,
    perf: 84,
    gaming: 69,
    ai: 62,
  },
  {
    id: "cpu-i7-265k",
    category: "cpu",
    brand: "Intel",
    family: "Core Ultra 7",
    name: "Core Ultra 7 265K",
    price: 419,
    power: 200,
    socket: "LGA1851",
    cores: 20,
    threads: 20,
    boostGhz: 5.5,
    cacheMb: 30,
    perf: 98,
    gaming: 73,
    ai: 78,
  },
  {
    id: "cpu-i9-285k",
    category: "cpu",
    brand: "Intel",
    family: "Core Ultra 9",
    name: "Core Ultra 9 285K",
    price: 589,
    power: 200,
    socket: "LGA1851",
    cores: 24,
    threads: 24,
    boostGhz: 5.7,
    cacheMb: 36,
    perf: 110,
    gaming: 74,
    ai: 85,
  },
];

export const motherboardParts: Part[] = [
  {
    id: "mb-b650m",
    category: "motherboard",
    brand: "ASUS",
    name: "TUF Gaming B650M-E",
    price: 139,
    power: 5,
    socket: "AM5",
    chipset: "B650",
    form: "mATX",
    ramMaxMhz: 6400,
    pcieGen: "Gen 4",
    tier: "mid",
    wifi: false,
    features: ["PCIe 4.0", "DDR5", "2x M.2", "mATX"],
  },
  {
    id: "mb-b650-plus-wifi",
    category: "motherboard",
    brand: "MSI",
    name: "B650 Gaming Plus WiFi",
    price: 179,
    power: 5,
    socket: "AM5",
    chipset: "B650",
    form: "ATX",
    ramMaxMhz: 6400,
    pcieGen: "Gen 4",
    tier: "mid",
    wifi: true,
    features: ["PCIe 4.0", "WiFi 6E", "DDR5", "3x M.2"],
  },
  {
    id: "mb-b650e",
    category: "motherboard",
    brand: "Gigabyte",
    name: "B650E Aorus Elite X AX",
    price: 259,
    power: 5,
    socket: "AM5",
    chipset: "B650E",
    form: "ATX",
    ramMaxMhz: 8000,
    pcieGen: "Gen 5",
    tier: "high",
    wifi: true,
    features: ["PCIe 5.0", "WiFi 6E", "DDR5", "4x M.2"],
  },
  {
    id: "mb-x670e",
    category: "motherboard",
    brand: "ASUS",
    name: "ROG Strix X670E-E",
    price: 499,
    power: 5,
    socket: "AM5",
    chipset: "X670E",
    form: "ATX",
    ramMaxMhz: 8000,
    pcieGen: "Gen 5",
    tier: "high",
    wifi: true,
    features: ["PCIe 5.0", "WiFi 6E", "USB4", "4x M.2"],
  },
  {
    id: "mb-x670e-taichi",
    category: "motherboard",
    brand: "ASRock",
    name: "X670E Taichi",
    price: 429,
    power: 5,
    socket: "AM5",
    chipset: "X670E",
    form: "EATX",
    ramMaxMhz: 8000,
    pcieGen: "Gen 5",
    tier: "high",
    wifi: true,
    features: ["PCIe 5.0", "WiFi 6E", "USB4", "5x M.2"],
  },
  {
    id: "mb-x870e",
    category: "motherboard",
    brand: "Gigabyte",
    name: "X870E Aorus Master",
    price: 589,
    power: 5,
    socket: "AM5",
    chipset: "X870E",
    form: "EATX",
    ramMaxMhz: 8000,
    pcieGen: "Gen 5",
    tier: "high",
    wifi: true,
    features: ["PCIe 5.0 x2", "WiFi 7", "USB4 40G", "5x M.2"],
  },
  {
    id: "mb-b760",
    category: "motherboard",
    brand: "MSI",
    name: "B760 Tomahawk WiFi",
    price: 149,
    power: 5,
    socket: "LGA1700",
    chipset: "B760",
    form: "ATX",
    ramMaxMhz: 6400,
    pcieGen: "Gen 4",
    tier: "mid",
    wifi: true,
    features: ["PCIe 4.0", "WiFi 6E", "DDR5", "3x M.2"],
  },
  {
    id: "mb-z790",
    category: "motherboard",
    brand: "Gigabyte",
    name: "Z790 Gaming X",
    price: 229,
    power: 5,
    socket: "LGA1700",
    chipset: "Z790",
    form: "ATX",
    ramMaxMhz: 6800,
    pcieGen: "Gen 4",
    tier: "mid",
    wifi: false,
    features: ["PCIe 5.0", "DDR5", "2x M.2"],
  },
  {
    id: "mb-z790-tomahawk",
    category: "motherboard",
    brand: "MSI",
    name: "Z790 Tomahawk WiFi",
    price: 259,
    power: 5,
    socket: "LGA1700",
    chipset: "Z790",
    form: "ATX",
    ramMaxMhz: 7200,
    pcieGen: "Gen 4",
    tier: "high",
    wifi: true,
    features: ["PCIe 5.0", "WiFi 6E", "DDR5", "4x M.2"],
  },
  {
    id: "mb-z790e",
    category: "motherboard",
    brand: "ASUS",
    name: "ROG Strix Z790-E",
    price: 419,
    power: 5,
    socket: "LGA1700",
    chipset: "Z790",
    form: "ATX",
    ramMaxMhz: 8000,
    pcieGen: "Gen 5",
    tier: "high",
    wifi: true,
    features: ["PCIe 5.0", "WiFi 6E", "DDR5", "4x M.2"],
  },
  {
    id: "mb-z790-aorus",
    category: "motherboard",
    brand: "Gigabyte",
    name: "Z790 Aorus Master",
    price: 459,
    power: 5,
    socket: "LGA1700",
    chipset: "Z790",
    form: "EATX",
    ramMaxMhz: 8000,
    pcieGen: "Gen 5",
    tier: "high",
    wifi: true,
    features: ["PCIe 5.0", "WiFi 6E", "DDR5", "5x M.2"],
    recommended: true,
  },
  {
    id: "mb-a620m",
    category: "motherboard",
    brand: "Gigabyte",
    name: "A620M Gaming X",
    price: 99,
    power: 5,
    socket: "AM5",
    chipset: "A620",
    form: "mATX",
    ramMaxMhz: 6400,
    pcieGen: "Gen 4",
    tier: "mid",
    wifi: false,
    features: ["PCIe 4.0", "DDR5", "2x M.2", "mATX"],
  },
  {
    id: "mb-b850",
    category: "motherboard",
    brand: "MSI",
    name: "B850 Gaming Plus WiFi",
    price: 199,
    power: 5,
    socket: "AM5",
    chipset: "B850",
    form: "ATX",
    ramMaxMhz: 8000,
    pcieGen: "Gen 5",
    tier: "mid",
    wifi: true,
    features: ["PCIe 5.0", "WiFi 7", "DDR5", "3x M.2"],
  },
  {
    id: "mb-x870",
    category: "motherboard",
    brand: "ASUS",
    name: "TUF Gaming X870-Plus WiFi",
    price: 279,
    power: 5,
    socket: "AM5",
    chipset: "X870",
    form: "ATX",
    ramMaxMhz: 8000,
    pcieGen: "Gen 5",
    tier: "high",
    wifi: true,
    features: ["PCIe 5.0", "WiFi 7", "USB4", "4x M.2"],
  },
  {
    id: "mb-b760m",
    category: "motherboard",
    brand: "Gigabyte",
    name: "B760M DS3H AX",
    price: 115,
    power: 5,
    socket: "LGA1700",
    chipset: "B760",
    form: "mATX",
    ramMaxMhz: 7600,
    pcieGen: "Gen 4",
    tier: "mid",
    wifi: true,
    features: ["PCIe 4.0", "WiFi 6E", "DDR5", "2x M.2", "mATX"],
  },
  {
    id: "mb-z790-tuf",
    category: "motherboard",
    brand: "ASUS",
    name: "TUF Gaming Z790-Plus WiFi",
    price: 249,
    power: 5,
    socket: "LGA1700",
    chipset: "Z790",
    form: "ATX",
    ramMaxMhz: 7200,
    pcieGen: "Gen 4",
    tier: "high",
    wifi: true,
    features: ["PCIe 5.0", "WiFi 6E", "DDR5", "4x M.2"],
  },
  {
    id: "mb-b860m",
    category: "motherboard",
    brand: "MSI",
    name: "B860M Gaming WiFi",
    price: 159,
    power: 5,
    socket: "LGA1851",
    chipset: "B860",
    form: "mATX",
    ramMaxMhz: 8600,
    pcieGen: "Gen 5",
    tier: "mid",
    wifi: true,
    features: ["PCIe 5.0", "WiFi 7", "DDR5", "3x M.2", "mATX"],
  },
  {
    id: "mb-z890-plus",
    category: "motherboard",
    brand: "MSI",
    name: "Z890 Gaming Plus WiFi",
    price: 239,
    power: 5,
    socket: "LGA1851",
    chipset: "Z890",
    form: "ATX",
    ramMaxMhz: 8800,
    pcieGen: "Gen 5",
    tier: "mid",
    wifi: true,
    features: ["PCIe 5.0", "WiFi 7", "DDR5", "4x M.2"],
  },
  {
    id: "mb-z890",
    category: "motherboard",
    brand: "ASUS",
    name: "ROG Strix Z890-E Gaming WiFi",
    price: 329,
    power: 5,
    socket: "LGA1851",
    chipset: "Z890",
    form: "ATX",
    ramMaxMhz: 9000,
    pcieGen: "Gen 5",
    tier: "high",
    wifi: true,
    features: ["PCIe 5.0", "WiFi 7", "USB4", "5x M.2"],
  },
];

export const gpuParts: Part[] = [
  {
    id: "gpu-rtx4060",
    category: "gpu",
    brand: "NVIDIA",
    family: "RTX 40",
    name: "GeForce RTX 4060",
    price: 299,
    power: 115,
    vramGb: 8,
    lengthMm: 240,
    psuMin: 550,
    perf: 58,
    gaming: 62,
    ai: 70,
  },
  {
    id: "gpu-rtx4060ti",
    category: "gpu",
    brand: "NVIDIA",
    family: "RTX 40",
    name: "GeForce RTX 4060 Ti 16 GB",
    price: 429,
    power: 160,
    vramGb: 16,
    lengthMm: 245,
    psuMin: 600,
    perf: 66,
    gaming: 72,
    ai: 76,
  },
  {
    id: "gpu-rtx5060",
    category: "gpu",
    brand: "NVIDIA",
    family: "RTX 50",
    name: "GeForce RTX 5060",
    price: 319,
    power: 145,
    vramGb: 8,
    lengthMm: 240,
    psuMin: 550,
    perf: 68,
    gaming: 71,
    ai: 79,
  },
  {
    id: "gpu-rx7600xt",
    category: "gpu",
    brand: "AMD",
    family: "RX 7000",
    name: "Radeon RX 7600 XT",
    price: 339,
    power: 150,
    vramGb: 16,
    lengthMm: 265,
    psuMin: 600,
    perf: 63,
    gaming: 67,
    ai: 55,
  },
  {
    id: "gpu-arc-b580",
    category: "gpu",
    brand: "Intel",
    family: "Arc B",
    name: "Arc B580",
    price: 269,
    power: 190,
    vramGb: 12,
    lengthMm: 270,
    psuMin: 600,
    perf: 58,
    gaming: 62,
    ai: 45,
  },
  {
    id: "gpu-rx7700xt",
    category: "gpu",
    brand: "AMD",
    family: "RX 7000",
    name: "Radeon RX 7700 XT",
    price: 399,
    power: 245,
    vramGb: 12,
    lengthMm: 285,
    psuMin: 650,
    perf: 73,
    gaming: 78,
    ai: 62,
  },
  {
    id: "gpu-rx7800xt",
    category: "gpu",
    brand: "AMD",
    family: "RX 7000",
    name: "Radeon RX 7800 XT",
    price: 499,
    power: 263,
    vramGb: 16,
    lengthMm: 330,
    psuMin: 700,
    perf: 80,
    gaming: 84,
    ai: 70,
  },
  {
    id: "gpu-rtx5060ti",
    category: "gpu",
    brand: "NVIDIA",
    family: "RTX 50",
    name: "GeForce RTX 5060 Ti",
    price: 449,
    power: 180,
    vramGb: 16,
    lengthMm: 242,
    psuMin: 600,
    perf: 78,
    gaming: 80,
    ai: 88,
  },
  {
    id: "gpu-rtx4070",
    category: "gpu",
    brand: "NVIDIA",
    family: "RTX 40",
    name: "GeForce RTX 4070",
    price: 579,
    power: 200,
    vramGb: 12,
    lengthMm: 300,
    psuMin: 650,
    perf: 76,
    gaming: 78,
    ai: 85,
  },
  {
    id: "gpu-rtx5070",
    category: "gpu",
    brand: "NVIDIA",
    family: "RTX 50",
    name: "GeForce RTX 5070",
    price: 589,
    power: 250,
    vramGb: 12,
    lengthMm: 280,
    psuMin: 650,
    perf: 88,
    gaming: 89,
    ai: 100,
  },
  {
    id: "gpu-rtx4070super",
    category: "gpu",
    brand: "NVIDIA",
    family: "RTX 40",
    name: "GeForce RTX 4070 Super",
    price: 669,
    power: 220,
    vramGb: 12,
    lengthMm: 305,
    psuMin: 700,
    perf: 82,
    gaming: 83,
    ai: 92,
  },
  {
    id: "gpu-rtx4070ti",
    category: "gpu",
    brand: "NVIDIA",
    family: "RTX 40",
    name: "GeForce RTX 4070 Ti",
    price: 759,
    power: 285,
    vramGb: 12,
    lengthMm: 305,
    psuMin: 750,
    perf: 90,
    gaming: 89,
    ai: 105,
  },
  {
    id: "gpu-rtx5070ti",
    category: "gpu",
    brand: "NVIDIA",
    family: "RTX 50",
    name: "GeForce RTX 5070 Ti",
    price: 769,
    power: 300,
    vramGb: 16,
    lengthMm: 305,
    psuMin: 750,
    perf: 98,
    gaming: 94,
    ai: 112,
  },
  {
    id: "gpu-rtx4070ti-super",
    category: "gpu",
    brand: "NVIDIA",
    family: "RTX 40",
    name: "GeForce RTX 4070 Ti Super",
    price: 879,
    power: 285,
    vramGb: 16,
    lengthMm: 320,
    psuMin: 750,
    perf: 92,
    gaming: 92,
    ai: 105,
  },
  {
    id: "gpu-rx9060xt",
    category: "gpu",
    brand: "AMD",
    family: "RX 9000",
    name: "Radeon RX 9060 XT 16 GB",
    price: 379,
    power: 160,
    vramGb: 16,
    lengthMm: 267,
    psuMin: 550,
    perf: 74,
    gaming: 77,
    ai: 68,
  },
  {
    id: "gpu-rx9070",
    category: "gpu",
    brand: "AMD",
    family: "RX 9000",
    name: "Radeon RX 9070",
    price: 569,
    power: 220,
    vramGb: 16,
    lengthMm: 290,
    psuMin: 700,
    perf: 90,
    gaming: 89,
    ai: 92,
  },
  {
    id: "gpu-rx9070xt",
    category: "gpu",
    brand: "AMD",
    family: "RX 9000",
    name: "Radeon RX 9070 XT",
    price: 649,
    power: 304,
    vramGb: 16,
    lengthMm: 320,
    psuMin: 750,
    perf: 96,
    gaming: 93,
    ai: 100,
  },
  {
    id: "gpu-rtx4080",
    category: "gpu",
    brand: "NVIDIA",
    family: "RTX 40",
    name: "GeForce RTX 4080",
    price: 1199,
    power: 320,
    vramGb: 16,
    lengthMm: 340,
    psuMin: 850,
    perf: 101,
    gaming: 94,
    ai: 118,
    render: 92,
  },
  {
    id: "gpu-rtx4080super",
    category: "gpu",
    brand: "NVIDIA",
    family: "RTX 40",
    name: "GeForce RTX 4080 Super",
    price: 1099,
    power: 320,
    vramGb: 16,
    lengthMm: 340,
    psuMin: 850,
    perf: 105,
    gaming: 98,
    ai: 125,
    render: 95,
  },
  {
    id: "gpu-rtx5080",
    category: "gpu",
    brand: "NVIDIA",
    family: "RTX 50",
    name: "GeForce RTX 5080",
    price: 1049,
    power: 360,
    vramGb: 16,
    lengthMm: 345,
    psuMin: 850,
    perf: 114,
    gaming: 98,
    ai: 128,
    render: 96,
  },
  {
    id: "gpu-rx7900xt",
    category: "gpu",
    brand: "AMD",
    family: "RX 7000",
    name: "Radeon RX 7900 XT",
    price: 699,
    power: 315,
    vramGb: 20,
    lengthMm: 310,
    psuMin: 800,
    perf: 95,
    gaming: 90,
    ai: 85,
  },
  {
    id: "gpu-rx7900xtx",
    category: "gpu",
    brand: "AMD",
    family: "RX 7000",
    name: "Radeon RX 7900 XTX",
    price: 999,
    power: 355,
    vramGb: 24,
    lengthMm: 350,
    psuMin: 1000,
    perf: 104,
    gaming: 97,
    ai: 95,
  },
  {
    id: "gpu-rtx4090",
    category: "gpu",
    brand: "NVIDIA",
    family: "RTX 40",
    name: "GeForce RTX 4090",
    price: 1949,
    power: 320,
    vramGb: 24,
    lengthMm: 360,
    psuMin: 1000,
    perf: 125,
    gaming: 100,
    ai: 150,
    render: 100,
    best: true,
  },
  {
    id: "gpu-rtx5090",
    category: "gpu",
    brand: "NVIDIA",
    family: "RTX 50",
    name: "GeForce RTX 5090",
    price: 2099,
    power: 575,
    vramGb: 32,
    lengthMm: 360,
    psuMin: 1200,
    perf: 135,
    gaming: 100,
    ai: 155,
    render: 100,
    best: true,
  },
];

// RAM genérica: sin marca, el cliente elige por capacidad y frecuencia.
export const ramParts: Part[] = [
  { id: "ram-16-4800", category: "ram", brand: "—", name: "16 GB DDR5 · 4800 MT/s", price: 49, memoryGb: 16, speed: "4800 MT/s · CL40", speedMhz: 4800, power: 4 },
  { id: "ram-16-5600", category: "ram", brand: "—", name: "16 GB DDR5 · 5600 MT/s", price: 59, memoryGb: 16, speed: "5600 MT/s · CL36", speedMhz: 5600, power: 4 },
  { id: "ram-32-5600", category: "ram", brand: "—", name: "32 GB DDR5 · 5600 MT/s", price: 95, memoryGb: 32, speed: "5600 MT/s · CL36", speedMhz: 5600, power: 6 },
  { id: "ram-32-6000", category: "ram", brand: "—", name: "32 GB DDR5 · 6000 MT/s", price: 115, memoryGb: 32, speed: "6000 MT/s · CL30", speedMhz: 6000, power: 6, recommended: true },
  { id: "ram-32-6400", category: "ram", brand: "—", name: "32 GB DDR5 · 6400 MT/s", price: 139, memoryGb: 32, speed: "6400 MT/s · CL32", speedMhz: 6400, power: 6 },
  { id: "ram-48-5600", category: "ram", brand: "—", name: "48 GB DDR5 · 5600 MT/s", price: 149, memoryGb: 48, speed: "5600 MT/s · CL38", speedMhz: 5600, power: 7 },
  { id: "ram-48-6000", category: "ram", brand: "—", name: "48 GB DDR5 · 6000 MT/s", price: 169, memoryGb: 48, speed: "6000 MT/s · CL30", speedMhz: 6000, power: 7 },
  { id: "ram-64-5600", category: "ram", brand: "—", name: "64 GB DDR5 · 5600 MT/s", price: 189, memoryGb: 64, speed: "5600 MT/s · CL38", speedMhz: 5600, power: 8 },
  { id: "ram-64-6000", category: "ram", brand: "—", name: "64 GB DDR5 · 6000 MT/s", price: 219, memoryGb: 64, speed: "6000 MT/s · CL30", speedMhz: 6000, power: 8, recommended: true },
  { id: "ram-96-5600", category: "ram", brand: "—", name: "96 GB DDR5 · 5600 MT/s", price: 299, memoryGb: 96, speed: "5600 MT/s · CL40", speedMhz: 5600, power: 9 },
  { id: "ram-128-5600", category: "ram", brand: "—", name: "128 GB DDR5 · 5600 MT/s", price: 499, memoryGb: 128, speed: "5600 MT/s · CL46", speedMhz: 5600, power: 10 },
];

// SSD genérico: sin marca, el cliente elige por capacidad y generación PCIe.
// Velocidades típicas reales por generación (lectura secuencial).
export const storageParts: Part[] = [
  { id: "ssd-500gb-g3", category: "storage", brand: "—", name: "500 GB NVMe · PCIe 3.0", price: 39, capacityTb: 0.5, speed: "3500 MB/s", pcieGen: "Gen 3", type: "NVMe", power: 4 },
  { id: "ssd-1tb-g3", category: "storage", brand: "—", name: "1 TB NVMe · PCIe 3.0", price: 49, capacityTb: 1, speed: "3500 MB/s", pcieGen: "Gen 3", type: "NVMe", power: 4 },
  { id: "ssd-2tb-g3", category: "storage", brand: "—", name: "2 TB NVMe · PCIe 3.0", price: 89, capacityTb: 2, speed: "3500 MB/s", pcieGen: "Gen 3", type: "NVMe", power: 5 },
  { id: "ssd-1tb-g4", category: "storage", brand: "—", name: "1 TB NVMe · PCIe 4.0", price: 65, capacityTb: 1, speed: "7000 MB/s", pcieGen: "Gen 4", type: "NVMe", power: 5, recommended: true },
  { id: "ssd-2tb-g4", category: "storage", brand: "—", name: "2 TB NVMe · PCIe 4.0", price: 119, capacityTb: 2, speed: "7000 MB/s", pcieGen: "Gen 4", type: "NVMe", power: 6, recommended: true },
  { id: "ssd-4tb-g4", category: "storage", brand: "—", name: "4 TB NVMe · PCIe 4.0", price: 259, capacityTb: 4, speed: "7100 MB/s", pcieGen: "Gen 4", type: "NVMe", power: 7 },
  { id: "ssd-8tb-g4", category: "storage", brand: "—", name: "8 TB NVMe · PCIe 4.0", price: 549, capacityTb: 8, speed: "7100 MB/s", pcieGen: "Gen 4", type: "NVMe", power: 8 },
  { id: "ssd-1tb-g5", category: "storage", brand: "—", name: "1 TB NVMe · PCIe 5.0", price: 119, capacityTb: 1, speed: "12000 MB/s", pcieGen: "Gen 5", type: "NVMe", power: 7 },
  { id: "ssd-2tb-g5", category: "storage", brand: "—", name: "2 TB NVMe · PCIe 5.0", price: 199, capacityTb: 2, speed: "12400 MB/s", pcieGen: "Gen 5", type: "NVMe", power: 8 },
  { id: "ssd-4tb-g5", category: "storage", brand: "—", name: "4 TB NVMe · PCIe 5.0", price: 389, capacityTb: 4, speed: "14100 MB/s", pcieGen: "Gen 5", type: "NVMe", power: 9 },
];

// Refrigeración genérica: sin marca, por tipo (aire/líquida) y variante.
// Alturas de torre y tamaños de radiador son valores típicos reales del segmento.
export const coolingParts: Part[] = [
  { id: "cool-air-single", category: "cooling", brand: "—", name: "Aire · Torre simple", price: 39, power: 2, type: "air", height: 155, features: ["Aire", "Torre simple"] },
  { id: "cool-air-dual", category: "cooling", brand: "—", name: "Aire · Doble torre", price: 59, power: 3, type: "air", height: 165, recommended: true, features: ["Aire", "Doble torre"] },
  { id: "cool-aio-120", category: "cooling", brand: "—", name: "Líquida · 120 mm (simple)", price: 75, power: 6, type: "aio", radiatorSupport: 120, features: ["Líquida AIO", "120 mm"] },
  { id: "cool-aio-240", category: "cooling", brand: "—", name: "Líquida · 240 mm (doble)", price: 109, power: 8, type: "aio", radiatorSupport: 240, recommended: true, features: ["Líquida AIO", "240 mm"] },
  { id: "cool-aio-360", category: "cooling", brand: "—", name: "Líquida · 360 mm (triple)", price: 159, power: 10, type: "aio", radiatorSupport: 360, features: ["Líquida AIO", "360 mm"] },
];

// Cajas genéricas por formato. maxGpuLength / maxCoolerHeight / radiatorMax /
// formSupport son valores típicos del formato (no de un modelo concreto).
export const caseParts: Part[] = [
  { id: "case-itx", category: "case", brand: "—", name: "Mini-ITX · Compacta (SFF)", price: 109, power: 0, maxGpuLength: 330, maxCoolerHeight: 155, size: "Mini-ITX", formSupport: ["ITX", "mATX"], radiatorMax: 240, fans: "2x 120 mm incluidos", features: ["SFF", "Compacta"] },
  { id: "case-matx", category: "case", brand: "—", name: "Micro-ATX · Compacta", price: 85, power: 0, maxGpuLength: 350, maxCoolerHeight: 160, size: "Micro-ATX", formSupport: ["mATX", "ITX"], radiatorMax: 240, fans: "2x 120 mm incluidos", features: ["Compacta", "Mesh"] },
  { id: "case-atx", category: "case", brand: "—", name: "ATX · Media torre", price: 99, power: 0, maxGpuLength: 370, maxCoolerHeight: 170, size: "ATX", formSupport: ["ATX", "mATX", "ITX"], radiatorMax: 360, fans: "3x 120 mm incluidos", recommended: true, features: ["Flujo de aire"] },
  { id: "case-atx-tg", category: "case", brand: "—", name: "ATX · Media torre cristal templado", price: 139, power: 0, maxGpuLength: 400, maxCoolerHeight: 175, size: "ATX", formSupport: ["ATX", "mATX", "ITX"], radiatorMax: 360, fans: "4x 120 mm incluidos", recommended: true, features: ["Cristal templado", "Showcase"] },
  { id: "case-eatx", category: "case", brand: "—", name: "E-ATX · Full tower", price: 219, power: 0, maxGpuLength: 450, maxCoolerHeight: 195, size: "E-ATX", formSupport: ["EATX", "ATX", "mATX", "ITX"], radiatorMax: 420, fans: "4x 140 mm incluidos", features: ["Full tower", "Doble cámara"] },
];

export const psuParts: Part[] = [
  { id: "psu-bronze-550", category: "psu", brand: "—", name: "550 W · 80+ Bronze", price: 79, power: 0, watts: 550, rating: "Bronze", form: "ATX" },
  { id: "psu-bronze-650", category: "psu", brand: "—", name: "650 W · 80+ Bronze", price: 99, power: 0, watts: 650, rating: "Bronze", form: "ATX" },
  { id: "psu-bronze-750", category: "psu", brand: "—", name: "750 W · 80+ Bronze", price: 109, power: 0, watts: 750, rating: "Bronze", form: "ATX" },
  { id: "psu-bronze-850", category: "psu", brand: "—", name: "850 W · 80+ Bronze", price: 129, power: 0, watts: 850, rating: "Bronze", form: "ATX" },
  { id: "psu-gold-550", category: "psu", brand: "—", name: "550 W · 80+ Gold", price: 109, power: 0, watts: 550, rating: "Gold", form: "ATX" },
  { id: "psu-gold-650", category: "psu", brand: "—", name: "650 W · 80+ Gold", price: 139, power: 0, watts: 650, rating: "Gold", form: "ATX", recommended: true },
  { id: "psu-gold-750", category: "psu", brand: "—", name: "750 W · 80+ Gold", price: 149, power: 0, watts: 750, rating: "Gold", form: "ATX", recommended: true },
  { id: "psu-gold-850", category: "psu", brand: "—", name: "850 W · 80+ Gold", price: 179, power: 0, watts: 850, rating: "Gold", form: "ATX" },
  { id: "psu-gold-1000", category: "psu", brand: "—", name: "1000 W · 80+ Gold", price: 229, power: 0, watts: 1000, rating: "Gold", form: "ATX" },
  { id: "psu-platinum-750", category: "psu", brand: "—", name: "750 W · 80+ Platinum", price: 189, power: 0, watts: 750, rating: "Platinum", form: "ATX" },
  { id: "psu-platinum-850", category: "psu", brand: "—", name: "850 W · 80+ Platinum", price: 209, power: 0, watts: 850, rating: "Platinum", form: "ATX" },
  { id: "psu-platinum-1000", category: "psu", brand: "—", name: "1000 W · 80+ Platinum", price: 249, power: 0, watts: 1000, rating: "Platinum", form: "ATX" },
  { id: "psu-platinum-1200", category: "psu", brand: "—", name: "1200 W · 80+ Platinum", price: 329, power: 0, watts: 1200, rating: "Platinum", form: "ATX" },
  { id: "psu-titanium-1000", category: "psu", brand: "—", name: "1000 W · 80+ Titanium", price: 319, power: 0, watts: 1000, rating: "Titanium", form: "ATX" },
  { id: "psu-titanium-1200", category: "psu", brand: "—", name: "1200 W · 80+ Titanium", price: 379, power: 0, watts: 1200, rating: "Titanium", form: "ATX" },
  { id: "psu-titanium-1600", category: "psu", brand: "—", name: "1600 W · 80+ Titanium", price: 519, power: 0, watts: 1600, rating: "Titanium", form: "ATX" },
];

export const osParts: Part[] = [
  { id: "os-none", category: "os", brand: "—", name: "Sin sistema operativo", price: 0, power: 0, noOs: true },
  { id: "os-win-home", category: "os", brand: "Microsoft", name: "Windows 11 Home", price: 129, power: 0 },
  { id: "os-win-pro", category: "os", brand: "Microsoft", name: "Windows 11 Pro", price: 219, power: 0 },
  { id: "os-ubuntu", category: "os", brand: "Canonical", name: "Ubuntu 24.04 LTS", price: 0, power: 0 },
];

// Monitores genéricos: sin marca, por pulgadas → tasa de refresco → panel.
// Los ultrawide 34"/49" se mapean a displayRes "1440p" para las estimaciones de FPS.
export const peripheralParts: Part[] = [
  { id: "mon-24-144-ips", category: "peripheral", brand: "—", name: "24\" · 144 Hz · IPS", price: 119, power: 26, kind: "monitor", monitorSize: "24\"", refreshHz: 144, panel: "IPS", displayRes: "1080p", features: ["1080p", "1 ms"] },
  { id: "mon-24-165-ips", category: "peripheral", brand: "—", name: "24\" · 165 Hz · IPS", price: 139, power: 28, kind: "monitor", monitorSize: "24\"", refreshHz: 165, panel: "IPS", displayRes: "1080p", features: ["1080p", "1 ms"], recommended: true },
  { id: "mon-27-144-ips", category: "peripheral", brand: "—", name: "27\" · 144 Hz · IPS", price: 219, power: 34, kind: "monitor", monitorSize: "27\"", refreshHz: 144, panel: "IPS", displayRes: "1440p", features: ["1440p", "1 ms"] },
  { id: "mon-27-165-ips", category: "peripheral", brand: "—", name: "27\" · 165 Hz · IPS", price: 259, power: 36, kind: "monitor", monitorSize: "27\"", refreshHz: 165, panel: "IPS", displayRes: "1440p", features: ["1440p", "1 ms"], recommended: true },
  { id: "mon-27-165-va", category: "peripheral", brand: "—", name: "27\" · 165 Hz · VA", price: 229, power: 36, kind: "monitor", monitorSize: "27\"", refreshHz: 165, panel: "VA", displayRes: "1440p", features: ["1440p", "Curvo"] },
  { id: "mon-27-240-oled", category: "peripheral", brand: "—", name: "27\" · 240 Hz · OLED", price: 599, power: 44, kind: "monitor", monitorSize: "27\"", refreshHz: 240, panel: "OLED", displayRes: "1440p", features: ["1440p", "0,03 ms", "HDR"] },
  { id: "mon-27-360-oled", category: "peripheral", brand: "—", name: "27\" · 360 Hz · OLED", price: 749, power: 48, kind: "monitor", monitorSize: "27\"", refreshHz: 360, panel: "OLED", displayRes: "1440p", features: ["1440p", "0,03 ms", "HDR"] },
  { id: "mon-32-144-ips", category: "peripheral", brand: "—", name: "32\" · 144 Hz · IPS", price: 449, power: 42, kind: "monitor", monitorSize: "32\"", refreshHz: 144, panel: "IPS", displayRes: "4k", features: ["4K", "HDMI 2.1"] },
  { id: "mon-32-165-va", category: "peripheral", brand: "—", name: "32\" · 165 Hz · VA", price: 399, power: 40, kind: "monitor", monitorSize: "32\"", refreshHz: 165, panel: "VA", displayRes: "4k", features: ["4K", "Curvo"] },
  { id: "mon-32-240-oled", category: "peripheral", brand: "—", name: "32\" · 240 Hz · OLED", price: 999, power: 55, kind: "monitor", monitorSize: "32\"", refreshHz: 240, panel: "OLED", displayRes: "4k", features: ["4K", "0,03 ms", "HDR"] },
  { id: "mon-34-165-va", category: "peripheral", brand: "—", name: "34\" · 165 Hz · VA · Ultrawide", price: 449, power: 46, kind: "monitor", monitorSize: "34\"", refreshHz: 165, panel: "VA", displayRes: "1440p", features: ["Ultrawide 21:9", "Curvo"] },
  { id: "mon-34-175-oled", category: "peripheral", brand: "—", name: "34\" · 175 Hz · OLED · Ultrawide", price: 749, power: 50, kind: "monitor", monitorSize: "34\"", refreshHz: 175, panel: "OLED", displayRes: "1440p", features: ["Ultrawide 21:9", "0,03 ms", "HDR"] },
  { id: "mon-49-240-oled", category: "peripheral", brand: "—", name: "49\" · 240 Hz · OLED · Superultrawide", price: 999, power: 60, kind: "monitor", monitorSize: "49\"", refreshHz: 240, panel: "OLED", displayRes: "1440p", features: ["Superultrawide 32:9", "0,03 ms", "HDR"] },
];

export const extraParts: Part[] = [
  { id: "extra-rgb-kit", category: "extra", brand: "Corsair", name: "Kit ventiladores RGB + controlador", price: 89, power: 15 },
  { id: "extra-capture", category: "extra", brand: "Elgato", name: "Tarjeta de captura HD60 X", price: 199, power: 0 },
  { id: "extra-wifi", category: "extra", brand: "Intel", name: "Módulo Wi-Fi 7 BE200", price: 39, power: 2 },
];

export const allParts: Part[] = [
  ...cpuParts,
  ...motherboardParts,
  ...gpuParts,
  ...ramParts,
  ...storageParts,
  ...coolingParts,
  ...psuParts,
  ...caseParts,
  ...osParts,
  ...peripheralParts,
  ...extraParts,
];

export function partById(id: string): Part | undefined {
  return allParts.find((p) => p.id === id);
}

export function partsByCategory(cat: Category): Part[] {
  return allParts.filter((p) => p.category === cat);
}